sudo: false
dist: trusty

language: go
go:
  - 1.8.3

git:
  depth: 1

script:
  - ./scripts/travis.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./public/
  fqdn: www.client9.com
  target_branch: master
  repo: https://github.com/client9/client9.github.io.git
  on:
    branch: master
