sudo: false

language: go
go:
  - 1.8.x

install:
  - ./godownloader-hugo.sh 0.20.7
  - go get github.com/tdewolff/minify/cmd/minify
  - go get github.com/client9/misspell/cmd/misspell
  - go get github.com/client9/s3push

script:
  - make compile

deploy:
  - provider: script
    skip_cleanup: true
    script: s3push
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: www.client9.com
    region: us-east-1
    local_dir: public
    skip_cleanup: true
    cache_control: "max-age=3600"
