sudo: false

language: go
go:
  - 1.8.x

install:
  - go get github.com/spf13/hugo
  - go get github.com/tdewolff/minify/cmd/minify

script:
  - make compile

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: www-draft-client9-com
    region: us-east-1
    local_dir: public-draft
    skip_cleanup: true
    cache_control: "no-cache"
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: www-client9-com
    region: us-east-1
    local_dir: public
    skip_cleanup: true
    cache_control: "max-age=3600"
