sudo: false

language: go
go:
  - 1.8.x

install:
  - go get github.com/spf13/hugo
  - go get github.com/tdewolff/minify/cmd/minify

script:
  - hugo -t client9
  - hugo -t client9 -D -E -F  -d public-draft
  - minify --html-keep-whitespace --html-keep-end-tags --html-keep-document-tags  -r -o public-draft public-draft

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: www-client9-com
    region: us-west-2
    endpoint: www-client9-com.s3-website-us-west-2.amazonaws.com
    local-dir: public
    skip_cleanup: true

