sudo: false

language: go
go:
  - 1.8.x

install:
  - go get github.com/spf13/hugo
  - go get github.com/tdewolff/minify/cmd/minify

script:
  - cp -f layouts/robots-all.txt layouts/robots.txt
  - hugo -t client9
  - minify --html-keep-whitespace --html-keep-end-tags --html-keep-document-tags -r -o public public
  - cp -f layouts/robots-none.txt layouts/robots.txt
  - hugo -t client9 -D -E -F -d public-draft
  - minify --html-keep-whitespace --html-keep-end-tags --html-keep-document-tags -r -o public-draft public-draft

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: www-draft-client9-com
    region: us-east-1
    local-dir: public-draft
    skip_cleanup: true

