baseurl = "http://www.client9.com/"
languageCode = "en-us"
title = "Nick Galbreath"
MetaDataFormat = "yaml"
enableRobotsTXT= true
googleAnalytics = ""

[params]
sitename="Nick Galbreath"
useWebFonts = true

