baseurl = "https://www.client9.com"
languageCode = "en"
title = "Nick Galbreath"
MetaDataFormat = "yaml"
enableRobotsTXT= true
googleAnalytics = ""
FootnoteReturnLinkContents = ""
copyright="&copy; 2018 Nick Galbreath"

[permalinks]
post="/:title/"
article="/article/:title"

[taxonomies]
tag="tags"

[params]
sitename="Nick Galbreath"
twitter="@NGalbreath"

[blackfriday]
extensions = ["footnotes"]
fractions = false
