baseurl = "https://www.client9.com"
languageCode = "en-us"
title = "Nick Galbreath"
MetaDataFormat = "yaml"
enableRobotsTXT= true
googleAnalytics = ""
FootnoteReturnLinkContents = "foo"
copyright="&copy; 2017 Nick Galbreath"
enableGitInfo = true

[permalinks]
post="/:title/"

[params]
sitename="Nick Galbreath"
twitter="@NGalbreath"

[blackfriday]
extensions = ["footnotes"]
