baseurl = "https://www.client9.com"
languageCode = "en"
title = "Nick Galbreath"
canonifyURLs = false
relativeURLs = false
MetaDataFormat = "yaml"
enableRobotsTXT= true
googleAnalytics = ""
FootnoteReturnLinkContents = ""
copyright="&copy; 2018 Nick Galbreath"
theme="client9"

[permalinks]
post="/:slug/"
article="/article/:slug"

[taxonomies]
tag="tags"

[params]
sitename="Nick Galbreath"
author="Nick Galbreath"
twitter="NGalbreath"
github="client9"

[blackfriday]
extensions = []
fractions = false
