#baseurl = "http://www-client9-com.s3-website-us-west-2.amazonaws.com"
baseurl = "https://www.client9.com"
languageCode = "en-us"
title = "Nick Galbreath"
MetaDataFormat = "yaml"
enableRobotsTXT= true
googleAnalytics = ""
FootnoteReturnLinkContents = "foo"
copyright="&copy; 2017 Nick Galbreath"
[params]
sitename="Nick Galbreath"
twitter="@NGalbreath"

[blackfriday]
extensions = ["footnotes"]
