baseurl = "http://www-client9-com.s3-website-us-west-2.amazonaws.com"
languageCode = "en-us"
title = "Nick Galbreath"
MetaDataFormat = "yaml"
enableRobotsTXT= true
googleAnalytics = ""

[params]
sitename="Nick Galbreath"
useWebFonts = true

